- ui/src/pages/Post/Comment.jsx
Fixes #11 
Ideally I feel like this should probably be handled in comment.go in the `stripDeletedInfo` function but it seemed like that would probably be a larger refactor that was likely undesired. 
Feel free to reject. <3
> Added a fix for deleted comments not showing pfp

- ui/index.html
This disables the website to zoom in on the input field when you tap on it, as that forces users to also manually zoom out to see all content
> Disable zoom on input field after tap

- ui/src/scss/_community.scss
Adding a slight shadow to comm profile pictures to make sure that comm profile pictures with a white background don't look odd/floating, ie. https://discuit.net/Amsterdam. This is a purely aesthetic change and doesn't change functionality, so I consider it subjective in nature. Feel free to reject, obviously.
> Adding slight shadow/border to community profile pictures

- README.md
- go.mod
This PR updates the `go.mod` file to specify Go version 1.21 since the `slices` package was added to the core library in Go 1.21.
> Update go.mod to use Go 1.21 as minimum required version

- ui/package.json
This PR updates the `watch` script in `package.json` to fix a typo (`webpak` instead of `webpack`) and to include the missing webpack config.
> Update watch script in package.json

- README.md
This PR updates the installation command from `libvips` to `libvips-dev` in `README.md`. While the `libvips` package itself is not required, `libvips-dev` is necessary for building the server because it's includes essential C headers.
> Update libvips install command in README

- ui/.eslintrc.js
To fix the recurring "CONFIG not defined" errors by adding `CONFIG` to the global constants in the eslintrc config.
> Add CONFIG to global constants in eslintrc config

- ui/.eslintrc.js
This update ensures that global objects (by example) as Promise and Unint8Array are recognized by ESLint, actually this is not the case.
> Enable ES2020 global variables

- Dockerfile
- README.md
- config.default.yaml
- docker/entrypoint.sh
- This PR supports building a docker image containing Discuit. It also updates from using a root user for the database to the `discuit` user
- Instructions are added to create the image and run the container
- Though if the config.yaml needs to be persisted, you will need to mount the file to the container
- Image is currently restricted to running on amd64 systems
Would close issue #4
> Add docker support

- Dockerfile
- docker/entrypoint.sh
Fix bug where if config.yaml is mounted, on reload the new config is not made use of in the UI. This was due to the `npm run build:prod` being in the docker image and using the example config & not using the new one. This was fixed by moving it to the `entrypoint.sh` file, where it will rebuild the UI on every restart of the container.
This was a mistake on my part for placing it in the wrong location.
> fix: bug in docker image with UI not loading new config.yaml

- config/config.go
- internal/httputil/httputil.go
- server/server.go
- ui/webpack.dev.js
- Fixes issue with `npm start` failing due to `contentBase: './dist'` in `webpack.dev.js`
- Allows setting of `devProxy` in config UI dev server
It should make it way easier to work on UI changes rather than having to `npm run build:local` on every update.
> feat: Add development proxy

- README.md
- docker/entrypoint.sh
The CLI command in the README and entrypoint script has been updated to use the new syntax. This change improves consistency and readability.
@previnder, forgot about updating some other locations where the CLI is used, they should all be good now, my bad
> chore: Update CLI command in README and entrypoint script

- ui/src/components/PostCard/embed.js
YouTube shorts do not currently embed properly ([example here](https://discuit.net/Cats/post/JIBgwHuY)).
This patch should extract the video ID from the shorts URL properly for embedding in Discuit.
> fix YouTube embeds for shorts

- core/feed.go
`postToComment` was having the `post.ID` overwritten by the next comment if it was for the same post, resulting in the comment missing the post title.
Fully closes: #91
> Fix: multple comments on same post in feed breaking post title

- ui/package-lock.json
- ui/package.json
- ui/webpack.dev.js
Creates a new npm script that allows developers to proxy webpack's dev server to https://discuit.net
This allows for easier FE development since FE devs simply need to kick off this start command and not worry about configuring a local backend
using `cross-env` to ensure it works regardless of OS
> Support proxying to discuit.net for easier frontend development

- ui/src/components/MarkdownBody.jsx
Fixes #102 
All internal links were previously handled with `Link`, this PR adds an exception for internal links that begin with `/images`, which will now instead use `a`.
> Fix: 404 when opening a Discuit image link from Discuit

- ui/src/App.jsx
- ui/src/scss/_base.scss
All of the other emojis seem to work fine, just this one that causes issues. We'll fix issues as they come up. If Inter causes too many issues we'll look for a new font, but in the meantime Inter seems to work fine (although some people on Discuit are not happy about the change).
You can also undo the other changes with the hacky temp fix if this PR is better.
Closes #108
> Exclude white large square emoji from Inter

- docker/entrypoint.sh
seems I forgot to update the entry point script to use the proper migrate command, so the docker container will keep restarting. My bad.
> chore: Update Docker entrypoint script to use proper migrate command

- ui/src/scss/_base.scss
Fixes flags and some other emojis not being displayed properly.
> Enable OpenType glyph composition

- ui/src/index.js
- ui/src/scss/_base.scss
Closes #110
Safari 16.0-16.3 doesn't automatically set the optical size of text causing small text to be rendered way too thin. This PR explicitly sets the optical size to 14 for the affected versions of Safari
14 was chosen as that's the minimum for Inter and would be most legible for smaller text
> Manually set optical size on Safari 16.0-16.3

- ui/src/scss/_components.scss
fixes dropdown menus being rendered below images, as reported [here](https://discuit.net/DiscuitMeta/post/Jsvg2NEh)
> ui: increase .dropdown z index

- cli/serve/serve.go
- config/config.go
- core/notification.go
- core/user.go
- migrations/0048_welcome_notification.down.sql
- migrations/0048_welcome_notification.up.sql
- ui/service-worker.js
- ui/src/components/Navbar/NotificationItem.jsx
This PR introduces a new notification type, `welcome`, which is sent to new users sometime after they sign up. Clicking on this notification sends users to a community, specified in the `welcomeCommunity` field of the `config.yaml`.
Right now, this notification is sent only a minute after a user signs up, but that value is used for testing purposes.
> User welcome notification

- cli/serve/serve.go
- core/notification.go
- core/post.go
- core/user.go
- migrations/0049_announcement_posts_table.down.sql
- migrations/0049_announcement_posts_table.up.sql
- server/post.go
- server/server.go
- ui/src/components/Navbar/notification.ts
- ui/src/pages/Post/index.jsx
- ui/src/serverTypes.ts
Introduces a new notification type to let all the users know of new announcements on the site; essentially, by sending a notification for the announcement post to all the users.
While working on this, however, it occurred to me how the notification rendering currently works—that is, on the front-end, using the structured objects returned from the server—is not ideal, especially for a site that uses the Web Push API for native notifications. The reason being that, in the current system, when a new notification type is introduced, the `service-worker.js` needs to be updated for the users to get the new notification via the Web Push API; and that that updating doesn't happen—and there's no way to make it happen—until the user visits the site. If the notification was rendered in a standard …
> Announcement notifications

- core/user.go
- migrations/0054_require_alt_text_user_config.down.sql
- migrations/0054_require_alt_text_user_config.up.sql
- ui/src/pages/NewPost/Image.tsx
- ui/src/pages/NewPost/index.tsx
- ui/src/pages/Settings/index.tsx
- ui/src/serverTypes.ts
adds a new user preference to require adding alt text to images before posting. this is **not** set locally & adds a new field, `require_alt_text`, to the `users` table. this is `false` by default. 
it's just a nice qol thing that helps you... *forces you* to remember to add alt text if you want it. 
if the option is enabled & an image doesn't have alt text, the alt text box will be outlined red and the "submit" button will be disabled. preview:
> add preference to require alt text when posting

- core/community.go
- core/user.go
- server/server.go
Mainly to move some data extraction of only-admin-readable fields into the `/api/users` endpoint. It is possible, but time-consuming, to extract the data of the relevant fields user-by-user ([via `adminsView`](https://github.com/discuitnet/discuit/blob/852a24ad62332de7fa39d16d833e40a95d9bbb98/server/user.go#L41)), and it makes more sense to make them available from `/api/users` since that is locked behind admins anyway. I believe this implementation in `scanUsers` should prevent leakage of the material for other users requesting data.
Additionally fixes a typo on the endpoint here ("DELTE"): `r.Handle("/api/community_requests/{requestID}", s.withHandler(s.deleteCommunityRequest)).Methods("DELTE")`
I've also added filtering to ignore deleted requests from the request extraction. Not sure …
> Tweak some admin endpoints
